[build-system]
requires = ["setuptools>=58.1.0", "wheel", "setuptools_scm[toml]>=6.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pyrano"
dynamic = ["version"]
description = "pyrano is a package to read and store data from pyranometers."
readme = "README.md"
authors = [
    { name = "Javier Gatón Herguedas", email = "gaton@goa.uva.es" },
]
maintainers = [
    { name = "Javier Gatón Herguedas", email = "gaton@goa.uva.es" },
]
requires-python = ">=3.9"
license = "LicenseRef-Proprietary"
license-files = ["LICENSE"]
classifiers=[
    "Private :: Do Not Upload",
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Natural Language :: English",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]
dependencies = [
    "pandas~=2.0",
    "pvlib~=0.12",
    "PyYAML~=6.0",
]

[project.optional-dependencies]
goadb-pymysql = ["goadb[mysql]~=0.0"] # MIT
goadb-mariadb = ["goadb[mariadb]~=0.0"] # LGPL
goadb-mysqlclient = ["goadb[mysqlclient]~=0.0"] # GPL
goadb-mysqlconnector = ["goadb[mysqlconnector]~=0.0"] # GPL
dev = ["pre-commit", "tox", "interrogate"]

[project.urls]
Homepage = "https://goa.uva.es"
Repository = "https://gitlab.com/goa-uva/pyrano.git"

[tool.setuptools.packages.find]
where = [""]
include = ["pyrano*"]

[tool.setuptools_scm]
root = "."
fallback_version = "1"

[tool.versioneer]
VCS = "git"
style = "pep440"
versionfile_source = "pyrano/_version.py"
versionfile_build = "pyrano/_version.py"
tag_prefix = ""
parentdir_prefix = ""

[tool.flake8]
exclude = ["docs"]
max-line-length = 120
extend-ignore = ["W291"]

[tool.mypy]
allow_untyped_globals = true
ignore_missing_imports = true

[tool.mypy-setup]
ignore_errors = true

[tool.mypy-tests]
ignore_errors = true

[tool.mypy-versioneer]
ignore_errors = true
